name=GC9A01A_t3n
version=1.1.0
author=Limor Fried, Adafruit, Paul Stoffregen, Kurt Eckhardt
maintainer=Kurt Eckhardt, Mike Smorto
sentence=Teensy support for GC9A01A (Circular 240x240 Color TFT)
paragraph=Uses Teensy(PJRC) T3.x and T4.x boards, allows use of different SPI buses
category=Display
url=https://github.com/mjs513/GC9A01A_t3n
architectures=*
dot_a_linkage=true
